import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Account() {

    const handleClickData = () => {
        console.log('データ削除')
    }

    const handleClickAccount = () => {
        console.log('アカウント削除')
    }

  return (
    <div>
        <Head>
            <title>wakaru | Account</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <button
            onClick={() => handleClickData()}
        >
            データ削除
        </button>
        <button
            onClick={() => handleClickAccount()}
        >
            アカウント削除
        </button>
    </div>
  )
}
