import Head from 'next/head'
import { Inter } from 'next/font/google'
import { deleteAccount, deleteDocument } from '@/firebase';
import Link from 'next/link';
import { router } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Account() {

    const handleClickData = async() => {
        console.log('データ削除');
        await deleteDocument();
        deleteAccount();
        router.push('/');
    }

  return (
    <div>
        <Head>
            <title>wakaru | Account</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Link href="/home">
            戻る
        </Link>
        <button
            onClick={() => handleClickData()}
        >
            データとアカウントを削除する
        </button>
    </div>
  )
}
